### ISSUE TITLE
view method for mol_frame not implemented

### ISSUE THREAD

**Issue by PatWalters** [apahl/mol_frame#2]
When I run this line in tutorial1.ipynb 
cpds.view(title="Some Molecules", fn="some_mols.html")
I get an attribute error for the view method 
~/software/mol_frame/mol_frame/mol_frame.py in __getattr__(self, name)
    160             return method
    161         else:
--> 162             raise AttributeError

Should this instead be 
from mol_frame.viewers import view
view(cpds,title="Some Molecules", fn="some_mols.html")

**Comment by apahl** [comment]
Hi Patrick,

cool that you are trying this library!

I have to apologize, I refactored the `view()` method into `write_tbl()`, because that name better describes what it does and I forgot to update the tutorial.

It is now updated and should work again.

Kind regards,  
Axel

**Comment by apahl** [comment]
Closed because of inactivity. Please feel free to re-open if required.
